spring.application.name=SIHMSystem

server.port=8029
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=SYSTEM
spring.datasource.password=system@123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

file.upload.directory.windows = C:/BSKY/
file.upload.directory.linux = /opt/BSKY/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=managemosaic@gmail.com
spring.mail.password=rfyvwfvmjpwkboab
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



file.roomImage.folder = RoomImage
file.tenant.doc = TenantDocument


file.roomImage.prifix = RMI
file.tenant.doc.prifix = TDC

